services:
  ui:
    image: ghcr.io/zab3355/portfolio-ui:latest
    env_file:
      - .env
    depends_on:
      - server
    ports:
      - "3001:80"  
    restart: unless-stopped

  server:
    image: ghcr.io/zab3355/portfolio-server:latest
    env_file:
      - .env
    ports:
      - "8080:8080" 
    restart: unless-stopped
